### ISSUE TITLE
Linux build - no static libraries

### ISSUE THREAD

**Issue by JamesBremner** [JamesBremner/knapsack#10]
Including the static versions of the standard libraries doe not work on Linux.

( reported in freelancer chat )

**Comment by JamesBremner** [comment]
When you have tested this, please close it.  Unless there is a problem, when assign it back to me with explanation

**Comment by Cashewfly** [comment]
The linux target is not finding pack2.h when compiling.   Adding the compiler argument

![image](https://user-images.githubusercontent.com/40144121/86258029-f1c9db00-bb7f-11ea-9344-f75b97be73f6.png)

solves the problem.  Note that this does not seem to be the correct 'codeblocks' solution, but it does work.

**Comment by JamesBremner** [comment]
Yikes!  Don'd do that.

**Comment by Cashewfly** [comment]
Perfect - It builds cleanly now.
