### ISSUE TITLE
DPS3UK dimension loop variable names

### ISSUE THREAD

**Issue by JamesBremner** [JamesBremner/knapsack#3]
In DP3UK the for loops though the dimensions use i,j,k for the loop variable names, meaning w, h, l.

In DPS3UK these names have been changed to use i,j,l.

This makes my head hurt!!!

The reason for the change is that the problem statement for DPS3UK uses k for the number of stages

My head just exploded!!!

I would like to do one of two things:

A.  Keep the dimension loop variables to i, j, k for both algorithms, and change the variable name k in the problem statement to `stageCount`

OR

B. Change the dimension loop variables in both algorithms to iwidth, iheight, ilength.

------------

Believe me, I usually do not bother a client with the name of loop variables.  However, you have expressed a strong concern about fidelity to the pseudo code variable names ( awful as they are! ) so I though I should run this past you before I do anything.

**Comment by Cashewfly** [comment]
Let's go with option B - iwidth, iheight, and ilength.  I completely understand your frustration and share it!  I am probably going to be out of contact for a couple hours...

**Comment by JamesBremner** [comment]
OK

**Comment by JamesBremner** [comment]
Done
