### ISSUE TITLE
Optimizing Inventory Returns

### ISSUE THREAD

**Issue by JamesBremner** [JamesBremner/knapsack#7]
> Optimizing what is returned to inventory is also a huge factor. Wood is too expensive to let any of it go unused.

The timber allocation algorithm we have been discussing in #6 arranges the ordered timber into levels of the same height.  It first does a number of G-cuts ( guillotine ) to produce sheets that are passed on to to a 2D allocation algorithm.  Lets call these cuts _L-cuts_.

I propose:

At startup, the contents of the specified inventory are ordered by their smallest dimension.  The timbers that are smaller than a specified limit are considered too "thin" to be considered  worth L-cutting.  They are moved to a section of inventory called _sheet_ inventory.  The larger timbers are moved to the _stock_ inventory.

The timbers in the sheet inventory are ordered by their second smallest dimension.  The timbers that are smaller than a specified limit are considered too "narrow" to be considered worth  splitting in the long dimension.   They are moved to a section of inventory called _scrap_ inventory.

Each timber in the order is checked to see if it can be allocated to a timber in the _scrap_ inventory with just one or zero cuts.  The order timbers that qualify are allocated to scrap using a 1D algorithm.

Each remaining order timber is checked to see if it can be allocated to a timber in the _sheet_ without using an _L-cut_   The order timbers that qualify are allocated to _sheet_ using a 2D algorithm.

The remaining order timbers are allocated from _stock_ by the full 3D algorithm discussed in #6.

When the cutting pattern is complete, the remaining bits of timber are filtered by their second smallest dimension.  Those that are below a specified limit are discarded.  The remainder are returned to inventory, scrap, sheet or stock as they qualify.

As an example:

![image](https://user-images.githubusercontent.com/2046227/85852921-99f63300-b77f-11ea-96c3-f345137b9776.png)

red indicates discard

yellow indicates to scrasp inventory

blue indicates to sheet inventory

**Comment by Cashewfly** [comment]
I can see the logic of doing it this way.   It's vaguely reminiscent of a 1d allocation system I'd looked at that could guarantee some performance bounds by calculating the specified limit used to determine whether to allocate on a primary or secondary pass.

**Comment by JamesBremner** [comment]
There will be a performance improvement if there are a lot of returns in the inventory, but the motivation is not to waste returns by ensuring they are used before large inventory items are chopped into little pieces.
